CC = gcc

TFLAG += -o

test: test/test.c source/file/file.c source/warn/warn.c source/strings/strings.c
	$(CC) $(TFLAG) run test/test.c source/file/file.c source/warn/warn.c source/strings/strings.c
	./run



clear:
	rm run
